name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g @sap/cds-dk
    - run: npm i
    - run: cd tests/incidents-app && npm i
    - run: npm run test
  integration-tests:
    runs-on: ubuntu-latest
    name: Integration Tests on Node.js ${{ matrix['node-version'] }} with ${{ matrix.hyperscaler }} and ${{ matrix['scanner-auth'] }} scanner auth
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x]
        hyperscaler: [AWS, AZURE]
        scanner-auth: [basic, mtls]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Integration tests
      uses: ./.github/actions/integration-tests
      with:
        CF_API: ${{ secrets[format('CF_API_{0}', matrix.hyperscaler)] }}
        CF_USERNAME: ${{ secrets['CF_USERNAME'] }}
        CF_PASSWORD: ${{ secrets['CF_PASSWORD'] }}
        CF_ORG: ${{ secrets[format('CF_ORG_{0}', matrix.hyperscaler)] }}
        CF_SPACE: ${{ secrets[format('CF_SPACE_{0}', matrix.hyperscaler)] }}
        OBJECT_STORE_KIND: ${{ vars[format('OBJECT_STORE_KIND_{0}', matrix.hyperscaler)] }}
        NODE_VERSION: ${{ matrix.node-version }}
        SCANNER_AUTH: ${{ matrix.scanner-auth }}
